version: '3.1'
services:
  avtdr-test-project:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - avtdr-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://avtdr-db:6540/tracks_db # следует указывать host-port
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  avtdr-db:
    image: postgis/postgis:15-3.4-alpine
    restart: always
    container_name: avtdr_tracks_db
    ports:
      - "6540:5432" #host/container
    environment:
      - POSTGRES_DB=tracks_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

 # avtdr-db:
 #   image: postgres:12-alpine
 #   container_name: avtdr_tracks_db
 #   ports:
 #     - "6540:5432"
 #   environment:
 #     - POSTGRES_DB=tracks_db
 #     - POSTGRES_USER=postgres
 #     - POSTGRES_PASSWORD=postgres